title: "My Casual Blog"
author: "Yiping"
description: "My first attempt with GitHub Page"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: Home}
  - {file: "archive.html", title: Blog}
  - {file: "math.html", title: Maths}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "yipingmiao929@gmail.com"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/yiping.miao.98/"}
  - {title: Facebook, icon: facebook, url: "https://www.facebook.com/yiping.miao.98"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
